apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: aleksys/orders
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8090
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8090
        env:
          - name: discovery.server-url
            value: http://discovery-server.default:8761/eureka
          - name: discovery.zone
            valueFrom:
              configMapKeyRef:
                key: discovery.zone
                name: discovery-config
          - name: discovery.hostname
            valueFrom:
              configMapKeyRef:
                key: orders.hostname
                name: discovery-config
